language: rust
before_script:
  - rustup component add rustfmt-preview
cache: cargo
script:
  - cargo test --verbose --all
  - cargo fmt --all -- --check
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
