language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

install:
  - rustup component add rustfmt || rustup component add rustmt-nightly

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose