language: rust
before_script:
  - rustup component add --toolchain stable rustfmt
  - rustup component add --toolchain beta rustfmt
  - rustup component add --toolchain nightly rustfmt-preview
cache: cargo
script:
  - cargo test --verbose --all
  - cargo fmt --all -- --check
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
