language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - rustup component add rustfmt || rustup component add rustmt-nightly || rustup component add rustfmt-preview

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose